version: '3.0'

services:
  db:
    container_name: hero-db-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "secret*"
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: "secret*"
    ports:
      - "33061:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    networks:
      - efcoredockermysql-net
  heroapi:
    depends_on:
      - db
    image: heroapp
    build: 
      context: .
    ports: 
      - "5000:80"
      - "5001:443"
    env_file: env-list
    volumes:
      - /Users/samuelrangel/Desktop/:/root/.dotnet/https
    networks:
      - efcoredockermysql-net
volumes:
  mysql-data:
networks:
  efcoredockermysql-net:
    driver: bridge