FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base
WORKDIR /app

EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env

WORKDIR /src
COPY hero.api.sln ./
COPY hero.transversal/*.csproj ./hero.transversal/
COPY hero.domain/*.csproj ./hero.domain/
COPY hero.infraestructure.EF/*.csproj ./hero.infraestructure.EF/
COPY hero.aplication/*.csproj ./hero.aplication/
COPY hero.api/*.csproj ./hero.api/

# Copy csproj and restore as distinct layers
RUN dotnet restore

# Copy everything else and build
COPY . .

WORKDIR /src/hero.transversal
RUN dotnet build -c Release -o /app

WORKDIR /src/hero.domain
RUN dotnet build -c Release -o /app

WORKDIR /src/hero.infraestructure.EF
RUN dotnet build -c Release -o /app

WORKDIR /src/hero.aplication
RUN dotnet build -c Release -o /app

WORKDIR /src/hero.api
RUN dotnet build -c Release -o /app

RUN dotnet publish -c Release -o /app

# Build runtime image
FROM base
WORKDIR /app
COPY --from=build-env /app .
ENTRYPOINT ["dotnet", "hero.api.dll"]